language: php
php:
    - 5.6
    - 7.0

script:
    - vendor/bin/tester tests -s -p php -c tests/php-unix.ini

before_script:
    - travis_retry composer update --no-interaction --prefer-dist $dependencies
